from typing import Any


class YoutubeDL:
    def __init__(self, params: Any = ...) -> None: ...
    def extract_info(self, url: str, download: bool = ...) -> Any: ...
    def prepare_filename(self, info_dict: Any) -> str: ...
    def __enter__(self) -> "YoutubeDL": ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...


class utils:
    class DownloadError(Exception): ...
