from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

NETSCAPE_HEADER = "\n".join(
    [
        "# Netscape HTTP Cookie File",
        "# Generated by METEOBOT (json -> netscape)",
        "# https://curl.se/docs/http-cookies.html",
        "",
    ]
)


def _to_netscape_line(cookie: dict[str, Any]) -> str:
    domain = str(cookie.get("domain") or "")
    host_only = bool(cookie.get("hostOnly", False))
    http_only = bool(cookie.get("httpOnly", False))

    if host_only:
        domain = domain.lstrip(".")
        include_sub = "FALSE"
    else:
        if not domain.startswith("."):
            domain = f".{domain}"
        include_sub = "TRUE"

    if http_only:
        domain = f"#HttpOnly_{domain}"

    path = str(cookie.get("path") or "/")
    secure = "TRUE" if cookie.get("secure", False) else "FALSE"

    exp = cookie.get("expirationDate", 0)
    if exp is None or cookie.get("session", False):
        exp_i = 0
    else:
        exp_i = int(math.floor(float(exp))) if exp else 0

    name = str(cookie.get("name") or "")
    value = str(cookie.get("value") or "")

    return "\t".join([domain, include_sub, path, secure, str(exp_i), name, value])


def convert_cookies(data: list[dict[str, Any]]) -> str:
    lines = [NETSCAPE_HEADER]
    lines.extend(_to_netscape_line(cookie) for cookie in data)
    return "\n".join(lines) + "\n"


def _load_json(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, dict):
        if "cookies" in data:
            data = data["cookies"]
        else:
            merged: list[dict[str, Any]] = []
            for value in data.values():
                if isinstance(value, list):
                    merged.extend(value)
            if merged:
                data = merged
    if not isinstance(data, list):
        raise ValueError("Input JSON must be a list or an object containing list values.")
    return data


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert browser-exported cookie JSON into Netscape cookies.txt."
    )
    parser.add_argument("input", type=Path, help="Path to cookies JSON file")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("cookies.txt"),
        help="Output cookies.txt path (default: cookies.txt)",
    )
    args = parser.parse_args()

    cookies = _load_json(args.input)
    args.output.write_text(convert_cookies(cookies), encoding="utf-8")
    print(f"Wrote {args.output} ({len(cookies)} cookies)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
